### ISSUE TITLE
Consider removing DID from `kid` of signature

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#156]
DID is already present in `metadata.from` and it's already a detached payload JWS so you have to have the rest of the message to verify the signature anyway

**Comment by decentralgabe** [comment]
it would be good to have the fully qualified kid (e.g. did:example:123#key-1) in there so just by looking at the JWS you can resolve the key material

**Comment by mistermoe** [comment]
agreed @decentralgabe . closing this out
