### ISSUE TITLE
Consider introducing endpoint that can be used to fetch information about PFI

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#160]
might be helpful to introduce an endpoint that responds with information like:
* supported version of tbDEX
* supported currency pairs

i'm thinking that it'll be beneficial for discovery purposes

**Comment by mistermoe** [comment]
related: #159

**Comment by jiyoontbd** [comment]
not sure if this is in line with what you were thinking for this endpoint, but a place where a PFI can put up a VC that can be used to verify the authenticity / trust-ability of the PFI would also be pretty neat. then Alice can grab the VC and ensure that she is indeed doing business with `Bank X`

**Comment by mahoekst** [comment]
Who would issue such a VC? I do think this is the approach to build trust models. Some specific DIDs of PFI but could also be something like, any PFI who holds a VC from regulator X for example.

**Comment by jiyoontbd** [comment]
the FDIC. or maybe the federal reserve? 😂 i imagine there is some organization that vets budding banks / financial institutions.

**Comment by KendallWeihe** [comment]
Sharing context from office hours: discussed adding the version to the PFIs DID doc, but concerned that different DID methods may support different service objects, so we may run into issues across DID methods

**Comment by mistermoe** [comment]
reference mentioned by @ALRubinger in office hours: [restful api maturity level 3](https://martinfowler.com/articles/richardsonMaturityModel.html#level3)

**Comment by mahoekst** [comment]
I am curious about the difference between did methods we are concerned about?

**Comment by ALRubinger** [comment]
Yep @mistermoe - the concept illustrated there is https://en.wikipedia.org/wiki/HATEOAS. It lets the client discover the API through hypermedia.

**Comment by phoebe-lew** [comment]
Wrapping this into versioning card
