### ISSUE TITLE
Finalize Interop Profile Proposal

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#173]
> [!IMPORTANT]
> Looking to finalize by November 28th EOD U.S.

will work with @decentralgabe to list out all of the various standards that should be supported

@decentralgabe can you describe the purpose of an interop profile and include your proposal here when it's ready?

**Comment by decentralgabe** [comment]
https://hackmd.io/@decentralgabe/SyR5ilhQ6/edit

**Comment by mahoekst** [comment]
Can we go ahead and create the different work items for the different pieces we need to implement and test?

**Comment by decentralgabe** [comment]
@mahoekst no this is blocked by approval and merge of the [profile here](https://github.com/TBD54566975/tbdex/pull/186), after that we can create work items.
