### ISSUE TITLE
Add an `external_id` field to message metadata to allow caller to provide arbitrary reference

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/tbdex#182]

**Comment by diehuxx** [comment]
I'm in favor of:
1. Adding `external_id` to the metadata for all TBDex messages. We have established a pattern that all message kinds have the same `metadata` schema and all resource kinds have the same `metadata` schema. We should stick to this simple and easy to implement/validate pattern.
2. Making NO RESTRICTION on `external_id`s in a given exchange.

**Comment by phoebe-lew** [comment]
@diehuxx what do you mean by `NO RESTRICTION`?

**Comment by diehuxx** [comment]
> what do you mean by NO RESTRICTION?

When @mistermoe and I were initially talking about this feature, we considered requiring all messages in a given exchange to have the same `external_id`. I.e. All messages with a given `exchange_id` will have the same `external_id`. I think now that that's a bit cumbersome and not necessarily more useful than allowing messages in a given exchange have different `external_id`s.
