### ISSUE TITLE
clarify error details

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex#204]
error message should look like this

```js
{
   errors: [
        {
            id: foo
            detail: bar,
            .. etc
        }
    ]
}
```

but that is not obvious by reading the http api spec

**Comment by andresuribe87** [comment]
Would it make sense to use problem details objects, as described in https://datatracker.ietf.org/doc/html/rfc9457, to convey errors in the http api spec?

**Comment by mistermoe** [comment]
@andresuribe87 it's currently modeled after [json api error objects](https://jsonapi.org/format/#error-objects)
