### ISSUE TITLE
[http-api] request tokens should be JWTs 

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#210]
currently, the request token used to authenticate requests like `GET /exchanges` is a JWS that include:

**Header**:
* `alg`
* `kid`

**Payload**:
* `timestamp`

I'm proposing that we shift to using [JWTs](https://datatracker.ietf.org/doc/html/rfc7519) instead.

 the JWT should contain the following:

**Header**:
* [`typ`](https://datatracker.ietf.org/doc/html/rfc7519#section-5.1): `JWT`.
   * we have all sorts of signatures and tokens flying around. setting `typ` to `JWT` as recommended by the JWT spec to provide a means to disambiguate
* [`kid`](https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.4): fully qualified verificationMethod ID. used to locate the verification method in a DID Document that should be used to verify the JWT signature
* [`alg`](https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.1): cryptographic algorithm used to compute the JWT signature

**Payload**:

* [`aud`](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3): the intended PFI's DID
  * In our existing setup, if a request token is compromised, it could potentially be misused with _any_ PFI. By incorporating the `aud` claim, we can limit the risk to just one PFI, thereby reducing the surface area for misuse.
* [`iss`](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1):  the requester's DID 
  * including to be informative. this is technically duplicative as the `kid` also includes the requester's DID 
* [`exp`](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4): expiration timestamp
  * limits the amount of time a compromised request token can be used. our current request tokens have no expiration. if one were compromised they could be used indefinitely. including `exp` limits the duration of the attack vector
* [`iat`](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6): when the JWT was created
  * including to be informative 
* [`jti`](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.7): used as a nonce to prevent replay attacks.
   * spec text should include more detail around exactly _how_ to prevent replay attacks 

TODOs:
PR to address this issue should:
- [ ] update relevant [spec text](https://github.com/TBD54566975/tbdex/tree/main/specs/http-api#authentication-2)
- [ ] re-generate test vectors.
- [ ] publish draft PR and await PRs for [JS](https://github.com/TBD54566975/tbdex-js/issues/122) and [KT](https://github.com/TBD54566975/tbdex-kt/issues/121)

**Comment by mistermoe** [comment]
cc: @jiyoontbd

**Comment by jiyoontbd** [comment]
the todos [here](https://github.com/TBD54566975/tbdex-js/blob/main/packages/http-client/src/client.ts#L273-L276) also mention adding `nbf` which is another timestamp. do we need this field in addition to `jti` (since that's essentially a timestamp as well)?

**Comment by mistermoe** [comment]
Good question @jiyoontbd! Can't think of a reason to include `nbf`. Down to leave it out if you are. Can't really see scenarios where people are generating and storing request tokens ahead of time that shouldn't be used until a specified time
