### ISSUE TITLE
Add support for delegation in the request JWT token

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/tbdex#238]
OR we should be more clear about the exceptions to this rule and how to handle them properly. Discussion after implementing a solution in tbdex-js: https://github.com/TBD54566975/tbdex-js/pull/176#issuecomment-1948680092

**Comment by KendallWeihe** [comment]
I think this comes to whether or not we should support delegation. The PR that is linked in the description enforces a verification rule which does not allow delegation, which I think is fine for the time being, but at some point we may want to extend support for delegation.

**Comment by decentralgabe** [comment]
Do we have a use case for delegation? If not I'd suggest closing this
