### ISSUE TITLE
Proposal: change `GET /exchanges` to return a list of exchange IDs instead of a list of exchanges

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#251]
This thought crossed my mind when considering how to support pagination for `GET /exchanges` and quickly realizing that it gets unwieldy quite fast. Without pagination we run the risk of returning massive response payloads. When attempting to include pagination, we can end up in situations where we may end up returning a _portion_ of an exchange. 

I think a better design might be to update `GET /exchanges` to return a list of exchange _IDs_ instead of entire exchanges. `GET /exchanges/:id` can then be used to retrieve all of the messages for a given exchange

**Comment by phoebe-lew** [comment]
For end of Q1, spec text changes with solutions for:
- how would we do pagination with current `GET /exchanges`?
- how do we prevent `GET /exchanges/:id` from getting hammered if `GET /exchanges` just returns a list of IDs?
