### ISSUE TITLE
make decimal point optional

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#253]
[here](https://github.com/TBD54566975/tbdex/blob/main/hosted/json-schemas/definitions.json#L10-L13)

making decimal point optional will prevent wallets from having to format user provided values. can get particularly annoying given that the appropriate number of significant digits varies for cryptocurrencies

this will not prevent treating numeric values as decimals especially given that all decimal libraries provide `parse(str)` functions that work with or without the decimal point

**Comment by KendallWeihe** [comment]
makes sense to me 👍
