### ISSUE TITLE
change `Offering.payoutUnitsPerPayinUnit` -> `Offering.rate`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#259]
`payoutUinitsPerPayinUnit` is so long. does make it undeniably evident what it is though

**Comment by mistermoe** [comment]
closing this out because `rate` is so ambiguous

**Comment by decentralgabe** [comment]
I had to read `payoutUnitsPerPayinUnit` and think about it before it clicked. Exchange rate is a common term, what about `exchangeRate`?
