### ISSUE TITLE
add `min` and `max` to `PaymentMethod`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#262]
[PaymentMethod](https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#paymentmethod) is the type used for the elements within `Offering.payinMethods[]` and `Offering.payoutMethods[]`.  it's quite possible that the min and max amounts can vary based on the payment method.

Proposing that we add optional `min` and `max` properties to `PaymentMethod` _in addition_ to `min` and `max` that already exist in [`CurrencyDetails`](https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#currencydetails).

`PaymentMethod` min & max would take precedence over `CurrencyDetails` min & max in situations where both are present.

**Comment by selfissued** [comment]
I'd try to mimic existing practices in the payments industry on this point.  I'm not an expert in those.  But maybe you have someone among your circle of experts who is?

**Comment by decentralgabe** [comment]
From digging through SWIFT I could not find an analogous concept; however, if LPs (fka PFIs) provide this type of data then I believe it would be useful to include in our `PaymentMethod`. Do we have any data to show that LPs have and will provide an estimate?

**Comment by decentralgabe** [comment]
I believe a construct like this is useful but I am worried about confusion / overlap between `PaymentMethod` and `CurrencyDetails`, specifically for the case where a `PaymentMethod` supports multiple currencies (e.g. a credit card that can pay with USD or EUR).

Should instead each `PaymentMethod` be associated with a set of `CurrencyDetails`?

**Comment by mistermoe** [comment]
@decentralgabe i believe your concern may be resolved by https://github.com/TBD54566975/tbdex/issues/260 ? lmk if i'm misunderstanding

**Comment by mistermoe** [comment]
also, an offering only ever has a single payin currency and a single payout currency. so that makes things easier

**Comment by decentralgabe** [comment]
if there can only ever be one single payin/payout then yes min/max makes sense to me
