### ISSUE TITLE
Consider `Close.success` exclusively valid for creation by the PFI

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/tbdex#288]
Ideated by @thehenrytsai [here](https://github.com/TBD54566975/tbdex/issues/280#issuecomment-2014152516)

> 1. Allow success to be exclusively used by the FPI to signal a "successful close" of the transaction.
> 2. If Alice tried to use success at all, treat it as an invalid message, even if it is set to false, just for simplicity of processing.

Relevant to the additions [here](https://github.com/TBD54566975/tbdex/pull/286/files)

Proposal here would be to update the spec with the above rules, and then notify implementors of additions needed

Requesting input from @mistermoe @phoebe-lew @jiyoontbd @kirahsapong @diehuxx

**Comment by KendallWeihe** [comment]
The major change here being: we're locking down Alice's ability to request a cancellation of an actively executing `Order`. Which is to say, once Alice submits an `Order`, they cannot undo that. We could open up that can of worms, but it creates additional complexity. If we feel we need that requirement then please voice that and we'll open that discussion.

**Comment by KendallWeihe** [comment]
> If we feel we need that requirement then please voice that and we'll open that discussion.

Actually, if we decide that's a requirement, then we'll decline this proposal and keep the spec as-is.

**Comment by KendallWeihe** [comment]
Alright, I'm closing this as not accepted, per the EFTA regulatory requirement. Thanks for pointing that out @kirahsapong 

The point to call out here is one of DX, that Alice may submit a `Close` but that doesn't guarantee a successful cancellation, and that our SDKs cannot make any enforcement of that, so it's up to the application to derive that state

**Comment by jiyoontbd** [comment]
adjusting why we closed - from what i'm reading, this is a `wontdo`
