### ISSUE TITLE
Replace mentions of ISO 3166 with ISO 4217

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#298]
raised by @thehenrytsai in https://github.com/TBD54566975/tbdex/issues/280

> Sanity: are both IOS 3166 currency code and ISO 4217 currency code used or just one of them (both are referenced in spec)?

[ISO 3166](https://www.iso.org/iso-3166-country-codes.html) is actually country codes and [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) is _currency_ codes so we want to use ISO 4217

**Comment by thehenrytsai** [comment]
This is now done.
