### ISSUE TITLE
Update Discovery README

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/tbdex#309]
The PFI Discovery info is out of date. Should be updated for v1
https://github.com/TBD54566975/tbdex/tree/main/discovery

**Comment by decentralgabe** [comment]
As far as I understand it discovery is out of scope for v1 - none of our SDKs support this or have a need to yet.

I agree the documents should be updated but it is a larger discussion: should we discuss a trust framework and discovery within that context? discovery with DID DHT or another registry? something else?

If a change is needed for v1 I would remove the discovery documents all together.

**Comment by angiejones** [comment]
> As far as I understand it discovery is out of scope for v1 - none of our SDKs support this or have a need to yet.
> 
> I agree the documents should be updated but it is a larger discussion: should we discuss a trust framework and discovery within that context? discovery with DID DHT or another registry? something else?
> 
> If a change is needed for v1 I would remove the discovery documents all together.

My vote is simply to remove for now so that no one is misled if they are reading through the repo

**Comment by mistermoe** [comment]
Yeah let's remove and resurface later when ready
