### ISSUE TITLE
Update offering.schema.json $ref

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex#311]
https://github.com/TBD54566975/tbdex/blob/main/hosted/json-schemas/offering.schema.json

add # to the $ref url `...json-schema.org...schema` at the end to help tbdex-dart consume the schemas

**Comment by ethan-tbd** [comment]
for additional context, tbdex-dart is using a [json_schema](https://github.com/Workiva/json_schema/blob/d843c4ad985b73361132926fec16c9b9c7043002/lib/src/json_schema/models/schema_version.dart#L79) dependency that requires the fragment `#` to be part of the schema url
