### ISSUE TITLE
Consider including a list of recommended order statuses

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#329]
the `orderStatus` property of an `OrderStatus` message is effectively plaintext which becomes quite difficult to wrangle especially from a wallet's perspective. We should include a list of recommended order statuses in the spec and a description of said status. 

Additionally, It would be helpful to provide these recommended order statuses as enums via our SDKs

Here's a few that come to mind immediately:

| Status             | Description                                                                              |
| :----------------- | :--------------------------------------------------------------------------------------- |
| `PAYIN_PENDING`    | Order has been received and PFI is waiting to receive the quoted payin amount from Alice |
| `PAYIN_RECEIVED`   | the quoted payin amount has been received by the PFI                                     |
| `PAYOUT_INITIATED` | the PFI has initiated the quoted payout                                                  |

**Comment by mistermoe** [comment]
cc: @angiejones

**Comment by jiyoontbd** [comment]
- payin_pending, payout_initiated as above, and add:
  - payin_settled
  - payin_failed
  - payin_expired
  - payout_pending
  - payout_initiated
  - payout_settled
  - payout_failed
- not `recommended`, but strongly type the orderstatus.status with the above string value and optional `details` field
  - optional `details` field can be populated by the PFI
- need order statuses for refund flow (i.e. when we receive a cancel message) related to #341 
  - refund_initiated
  - refund_pending
  - refund_failed
  - refund_settled
