### ISSUE TITLE
Clarify what's included in `fee` and `amount` in tbdex Quote

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex#331]
alice is using USD to send bob some MXN. 

given this offering:
```javascript
offering = {
    payoutUnitsPerPayinUnit: 16.00,
    payin: {
        methods: [
            {
                kind: 'CREDIT_CARD',
                fee: 0.25,
                min: 10,
                max: 100000,
            }
        ]
    },
    ...
}
```

then we can submit the RFQ like this
```javascript
rfq = {
    payin: {
        amount: 100,
        kind: 'CREDIT_CARD',
        ...
    }
...
}
```

we can represent the quote in 3 ways. there's a couple questions:

1. how much should the PFI charge alice? 
    - Option A: $100.00 (same as rfq.payin.amount, that **includes** PFI's fee)
    - Option B: $100.25 (rfq.payin.amount **plus** PFI's fee on **top**)
3. which representation is the correct one?
4. how should the wallet consume and display the `amount` and `fee` returned from the Quote?

```javascript
// alice pays $100.25 in total. bob gets 1661 MXN ($100.00 USD equivalent)
quote1 = {
    payin: {
        rate: 16.00,
        amount: 100, // <- this amount reflects actual USD to be converted to MXN, fee is NOT subtracted before conversion
        fee: 0.25
    },
    payout: {
        amount: 1600 // 100.00 * 16.00
    }
}

// alice pays $100.00 in total. bob gets 1596 MXN ($99.75 USD equivalent)
quote2 = {
    payin: {
        rate: 16.00,
        amount: 100, // <- this amount reflects total USD alice pays, including fees. fee IS subtracted before conversion
        fee: 0.25
    },
    payout: {
        amount: 1596 // 99.75 * 16.00
    }

}

// alice pays $100.00 in total. bob gets 1596 MXN ($99.75 USD equivalent)
quote3 = {
    payin: {
        rate: 16.00,
        amount: 99.75, // <- this amount reflects actual USD to be converted to MXN, fee IS subtracted before conversion
        fee: 0.25
    },
    payout: {
        amount: 1596 // 99.75 * 16.00
    }

}

**Comment by jiyoontbd** [comment]
@corcillo @mistermoe @ethan-tbd @yuntianlong2002

**Comment by jiyoontbd** [comment]
relevant PR w/ comments: https://github.com/TBD54566975/tbdex/pull/198

**Comment by nburgess48** [comment]
Was wiring funds to a business today via Bank of America, and thought the way they handled this was pretty intuitive. The amount I wanted to send the business (i.e. the amount I entered in via my BofA wallet) was $1,162.58:
![IMG_3998](https://github.com/TBD54566975/tbdex/assets/92107822/b67ea3b8-f141-4c97-9a99-14d358aca470)

**Comment by jiyoontbd** [comment]
so per our last meeting i think we decided:

* add `total_amount` as a field which is always `amount + fee` - this means amount never includes fee

gonna work on spec changes given this is the correct decision

cc @mistermoe
